routes/web.php
<?php

use App\Tea;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


    // TOLDO rewrite to a controller, have it 
Route::get('/', function () {
    // TODO add top four teas.
    $teas = Tea::all()->sortByDesc('AverageRating')->take(4);
    $users = User::all()->sortByDesc('NumberOfReviews')->take(4);
    return view('pages.index', compact('teas','users'));
})->name('home');


Route::resource('tea', 'TeaController',
    ['except' => 
    ['show']
    ]);

Route::get('tea/{tea}/{slug?}', 'TeaController@show')->name('tea.show');

Route::resource('review', 'ReviewController',
    ['except' => 
    ['create']
    ]);

Route::get('review/create/{id}', 'ReviewController@create')->name('review.create');

Route::resource('user', 'UserController');

Route::get('pages/verified', function () {
    return view('pages.verified');
})->name('verified_review');


Route::get('about_us', function (){
    return view('pages.about_us');
})->name('about_us');
Route::get('faq', function (){
    return view('pages.faq');
})->name('faq');
Route::get('terms_and_conditions', function (){
    return view('pages.tnc');
})->name('tnc');


Route::get('phpinfo', function () {
    return phpinfo();
});



Route::get('/home', 'HomeController@index');

// Let a user add a tearoom (innit).
Route::get('tearoom/main','TearoomController@create');

Route::post('tearoom', 'TearoomController@store');

Route::get('api/v2/users/{user}/reviews', 'UserController@reviews')->name('users.reviews');

Auth::routes();

app/Http/Controllers/ReviewController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

// use App\Review;
use App\Http\Requests;
use App\Review;
use App\Tea;

class ReviewController extends Controller
{
    /**
     * Display a listing of the resource.teas
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
    }


    public function __construct()
    {
        // magic suggested by ryan, lets only logged in users see the create page.
        $this->middleware('auth', ['only' => ['create']]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create($id)
    {
        $tea = Tea::find($id);
        // dd($tea);
        return view('reviews.create', compact('tea'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        // 1. Validate the data
        $this->validate($request, [
            'tea_id' => 'required',
            'rating' => 'required|numeric|min:0|max:100',
            'content' => 'required|min:4|max:16000'
        ]);

        // Extracts and validates.

        $review = Review::create([
            'tea_id' => $request->input('tea_id'),
            'user_id' => Auth::user()->id,
            'rating' => $request->input('rating'),
            'content' => $request->input('content'),
            'verified' => '1',
        ]);

        // 4. Redirect to a view.
        // TOLDO 
        return redirect()->route('tea.show', ['id' => $request->input('tea_id')]);

    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        if ($review = Review::find($id)){
            // $company = Company::find($tea->company_id);
            return view('reviews.show', compact('review'));
        }
        else{
            // return view('errors.teaNotFound');
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Review $review)
    {

        // example by nathan.
        $review->name = 'thing';
        $review->save();

        $review->update(['name' => 'thing']);


    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }

    public function verified()
    {
        return view('reviews.verified');
    }


}

resources/views/reviews/create.blade.php
@extends('layouts.app')

@section('content')

<p>
    Please add a review for an existing tea. 
    If you cannot find it, then have a look at <a href="{{route('tea.create')}}">here</a>.
</p>


    <form class="form-horizontal" action="{{ route('review.store') }}" method="post">

        <!-- ensure that the form can pass CSRF protection -->
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label for="tea_id" class="col-sm-2 control-label">Tea reviewed:</label>
            <div class="col-sm-10">
              <input name="tea_id" type="hidden" class="form-control" id="tea_id" value="{{$tea->id}}">
                <h5>{{$tea->name}} by {{$tea->company->name}}</h5>
            </div>
        </div>

        <div class="form-group">
            <label for="rating" class="col-sm-2 control-label">Rating (0-100)</label>
            <div class="col-sm-10">
                <input name="rating" type="number" id="replyNumber" min="0" step="1" max="100" data-bind="value:replyNumber" />
            </div>
        </div>

        <div class="form-group">
            <label for="content" class="col-sm-2 control-label">Review Text</label>
            <div class="col-sm-10">
              <textarea name="content" type="text" class="form-control" id="content" placeholder="Review, decribe your experience." maxlength="16000" minlength="10"></textarea>
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <button class="btn btn-primary">Create!</button>
            </div>
        </div>

    </form>

@stop

resources/views/reviews/show.blade.php
@extends('layouts.app')

@section('content')

    <h1> Review : {{ $review}}</h1>

    <p>
        This is the tea: {{$review->tea}}
    </p>


@stop