routes/web.php
<?php

use App\Tea;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


    // TOLDO rewrite to a controller, have it 
Route::get('/', function () {
    // TODO add top four teas.
    $teas = Tea::all()->sortByDesc('AverageRating')->take(4);
    $users = User::all()->sortByDesc('NumberOfReviews')->take(4);
    return view('pages.index', compact('teas','users'));
})->name('home');


Route::resource('tea', 'TeaController',
    ['except' => 
    ['show']
    ]);

Route::get('tea/{tea}/{slug?}', 'TeaController@show')->name('tea.show');

Route::resource('review', 'ReviewController',
    ['except' => 
    ['create']
    ]);

Route::get('review/create/{id}', 'ReviewController@create')->name('review.create');

Route::resource('user', 'UserController');

Route::get('pages/verified', function () {
    return view('pages.verified');
})->name('verified_review');


Route::get('about_us', function (){
    return view('pages.about_us');
})->name('about_us');
Route::get('faq', function (){
    return view('pages.faq');
})->name('faq');
Route::get('terms_and_conditions', function (){
    return view('pages.tnc');
})->name('tnc');


Route::get('phpinfo', function () {
    return phpinfo();
});



Route::get('/home', 'HomeController@index');

// Let a user add a tearoom (innit).
Route::get('tearoom/main','TearoomController@create');

Route::post('tearoom', 'TearoomController@store');

Route::get('api/v2/users/{user}/reviews', 'UserController@reviews')->name('users.reviews');

Auth::routes();

app/Tea.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tea extends Model
{

    // lets you edit these things.
    protected $fillable = [
        'name',
        'type',
        'company_id',
        'image_file',
        'image_extension',
    ];

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function reviews()
    {
        return $this->hasMany('App\Review');
    }

    public function getAverageRatingAttribute()
    {
        return round($this->reviews()->avg('rating'));
    }

    public function getImageLocationAttribute()
    {
        return "/images/tea/". $this->image_file . $this->image_extension;
    }

    public function getUrlAttribute()
    {
        return route('tea.show', ['id' => $this->id, 'slug' => $this->slug]);
    }

public function getSlugAttribute()
    {
        return str_slug($this->name);
    }


}

app/Http/Controllers/TeaController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Tea;
use App\Company;
use App\Http\Requests;

class TeaController extends Controller
{

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $teas = Tea::all();
        $teas = $teas->sortByDesc('AverageRating');

        return view('teas.index',compact('teas'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('teas.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id, $slug = null)
    {

        // handles the two different types of pages.
        if ($tea = Tea::find($id)){

            // Added the reviews for the item.
            $reviews = Tea::find($id)->reviews;
            // $tea->average = round($tea->reviews()->avg('rating'));

            // adam showed me this way of adding a slug.
            return $tea->slug == $slug
                ? view('teas.show', compact('tea','reviews'))
                : redirect($tea->url);
        }
        else{
            return view('errors.teaNotFound');
        }
    }

// public function show(Country $country, $slug = null)

//     {

//         return $country->slug == $slug

//             ? view('search.cities', compact('country'))

//             : redirect($country->url);

//     }


    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }



}

resources/views/teas/create.blade.php
@extends('layouts.app')

@section('content')

<p>
    Please add a tea which our website doesn't have.
    Have a search on our site for it first.
</p>

    <!-- TODO add a search bar in here to search existing teas. -->

    <form class="form-horizontal" action="{{ route('tea.store') }}" method="post">

        <!-- ensure that the form can pass CSRF protection -->
        <input type="hidden" name="_token" value="{{ csrf_token() }}">

        <div class="form-group">
            <label for="name" class="col-sm-2 control-label">Name</label>
            <div class="col-sm-10">
                <input name="name" type="text" class="form-control" id="name" placeholder="Name">
            </div>
        </div>

        <div class="form-group">
            <label for="company_id" class="col-sm-2 control-label">Company ID</label>
            <div class="col-sm-10">
              <input name="company_id" type="replyNumber" class="form-control" id="company_id" placeholder="ID of company">
            </div>
        </div>

        <div class="form-group">
            <label for="type" class="col-sm-2 control-label">Tea Type</label>
            <div class="col-sm-10">
              <input name="type" type="text" class="form-control" id="type" placeholder="Description">
            </div>
        </div>
    
        <div class="form-group">
            <div class="col-sm-10 col-sm-offset-2">
                <button class="btn btn-primary">Create!</button>
            </div>
        </div>

    </form>



@stop

resources/views/teas/index.blade.php
@extends('layouts.app')

@section('content')


<!-- This is now a landing page for all the teas we have offer. -->

<h1>Explore our highly rated teas</h1>

<h2>We have {{count($teas)}} teas on our site!</h2>

<h3>
    Can't find a tea you want to review?

    @if (Auth::check())
        <a href="{{ route('tea.create') }}">
            <button class="btn" >
                Add a tea<span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
            </button>
        </a>
    @else
        Join us, <a href="{{ url('/register') }}">Sign Up</a>
    @endif
</h3>




<div class="row">
    @foreach ($teas as $tea)
        <div class="col-xs-6 col-sm-4 col-md-3 tea-box">
            <a href="{{ $tea->url }}" class="thumbnail">
                <img src='{{$tea->ImageLocation}}' alt="image of {{ $tea->name }}" class="tea_image">
            </a> 
            <div class="caption">
                {{ $tea->name }}
                is a {{ $tea->type }} tea, 
                by <a href="{{$tea->company->url}}" target="_blank">{{$tea->company->name }}</a>.
                
                <h3 class="text-center">
                    {{count($tea->reviews)}} 
                    <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                </h3>
            </div>

        <div class="progress">
            <div class="progress-bar" role="progressbar" aria-valuenow="{{$tea->averageRating}}" aria-valuemin="0" aria-valuemax="100" style="width: {{$tea->averageRating}}%;">
                {{$tea->averageRating}} 
            </div>
        </div>

        </div>
    @endforeach
</div>

@endsection

resources/views/teas/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container-fluid">
<div class="row">
    <div class="col-xs-12 col-md-6">
        <h1> {{ $tea->name }}</h1>

        <h2>Made by <a href="{{$tea->company->url}}">{{$tea->company->name }}</a></h2>

        <h3> Type of Tea : {{ $tea->type  }}</h3>

        <h3> Average Tea Rating: {{ $tea->averageRating }} / 100</h3>

        <h3>
            Buy 
            <a href="{{$tea->buy_url}}" target="_blank">
                <button  class="btn btn-primary btn-sm" >
                    <i class="fa fa-coffee" aria-hidden="true"></i>
                </button>
            </a>
            from a 3rd party retailer
        </h3>

            <a href="https://twitter.com/share" class="twitter-share-button" data-show-count="false">Tweet</a><script async src="//platform.twitter.com/widgets.js" charset="utf-8"></script>

            <!-- Made the button by fiddling in css heavily. -->
            <!-- http://stackoverflow.com/questions/16463030/how-to-add-facebook-share-button-on-my-website -->
            <a href="https://www.facebook.com/sharer/sharer.php?u={{Request::fullurl()}}" target="_blank" class='fb_button'>
                Share on Facebook
            </a>
            <!-- https://developers.google.com/+/web/share/ Had to fiddle in css again, now is same height as the other two. -->
            <a href="https://plus.google.com/share?url={{Request::url()}}" onclick="javascript:window.open(this.href,
              '', 'menubar=no,toolbar=no,resizable=yes,scrollbars=yes,height=600,width=600');return false;"><img
              src="/images/gplus-21.png" alt="Share on Google+" class="google-btn"/></a>
    </div>
    <div class="col-xs-12 col-md-6 tea-image-box">
        <img src='{{$tea->ImageLocation}}' alt="image of {{ $tea->name }}">
    </div>
</div>

</div>


    <!-- Button for sharing on twitter. -->
    <!-- $reviews = Tea::all()->reviews; -->

    @foreach ($reviews as $review) 

        <div class="panel panel-default">
            <div class="panel-heading">
                <img src="{{ url($review->user->ImageLocation) }}" alt="{{ $review->user->username }}'s' avatar image">
                <a href="{{route('user.show',['id' => $review->user])}}">{{$review->user->username}}</a>
                Rating: {{ $review->rating }} / 100

                @if ($review->verified == 1)
                <div class="pull-right">
                    <button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#verifiedModal">
                        <span class="glyphicon glyphicon-ok" aria-hidden="true"></span>
                    </button>
                    Verified review
                </div>
                @endif

            </div>
            <div class="panel-body">
                {{ $review->content }}
            </div>
        </div>
<!-- 
        <h3>Review by {{$review->user->username}}</h3>

        <h3> {{ $review->content }}</h3>
 -->
        <!-- {{$review}} -->

    @endforeach




<!-- Modal for the verified button.-->
<div class="modal fade" id="verifiedModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">
          What is a verified review?
        </h4>
      </div>
      <div class="modal-body">
        A verified review is one where we can guarantee that the item in question was purchased by the user.
        We cannot yet verify that users are disclosing any financial interests.
        Adding a simple disclaimer to your review is enough
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <a href="{{ route('verified_review') }}" class="btn btn-info" role="button">Find Out More</a>
      </div>
    </div>
  </div>
</div>

<!-- Bottom section to give the users a link to post reviews but sign up if not logged in. -->
<div class="text-center">
    <h3>
        Would you like to add your review here?
    </h3>
    <br>
    @if (Auth::check())
        <a href="{{ route('review.create', ['id' => $tea->id])}}">
            <button type="button" class="btn btn-default btn-lg">
                    <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
            </button>
        </a>
    @else
        <h2> 
            <a href="{{ url('/register') }}">Sign Up</a>
            /
            <a href="{{ url('/login') }}">Login</a>
        </h2>
    @endif
</div>
<br>

@stop