routes/web.php
<?php

use App\Tea;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


    // TOLDO rewrite to a controller, have it 
Route::get('/', function () {
    // TODO add top four teas.
    $teas = Tea::all()->sortByDesc('AverageRating')->take(4);
    $users = User::all()->sortByDesc('NumberOfReviews')->take(4);
    return view('pages.index', compact('teas','users'));
})->name('home');


Route::resource('tea', 'TeaController',
    ['except' => 
    ['show']
    ]);

Route::get('tea/{tea}/{slug?}', 'TeaController@show')->name('tea.show');

Route::resource('review', 'ReviewController',
    ['except' => 
    ['create']
    ]);

Route::get('review/create/{id}', 'ReviewController@create')->name('review.create');

Route::resource('user', 'UserController');

Route::get('pages/verified', function () {
    return view('pages.verified');
})->name('verified_review');


Route::get('about_us', function (){
    return view('pages.about_us');
})->name('about_us');
Route::get('faq', function (){
    return view('pages.faq');
})->name('faq');
Route::get('terms_and_conditions', function (){
    return view('pages.tnc');
})->name('tnc');


Route::get('phpinfo', function () {
    return phpinfo();
});



Route::get('/home', 'HomeController@index');

// Let a user add a tearoom (innit).
Route::get('tearoom/main','TearoomController@create');

Route::post('tearoom', 'TearoomController@store');

Route::get('api/v2/users/{user}/reviews', 'UserController@reviews')->name('users.reviews');

Auth::routes();

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Styles -->
    <link href="/css/app.css" rel="stylesheet">

    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="/css/css.css" rel="stylesheet">

    @yield('heading')

    
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.3/css/font-awesome.min.css">

    <!-- Scripts -->
    <script>
        window.Laravel = <?php echo json_encode([
            'csrfToken' => csrf_token(),
        ]); ?>
    </script>
</head>
<body>
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{{ url('/') }}">
                    <i class="fa fa-coffee" aria-hidden="true"></i>
                    {{ config('app.name', 'Laravel') }}
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{{ route('tea.index') }}">Teas</a></li>
                    <!-- <li><a href="#">Places</a></li> -->
                    <li><a href="{{ route('user.index') }}">Users</a></li>
                    <!-- <li><a href="#">Community</a></li> -->
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    @if (Auth::guest())
                        <li><a href="{{ url('/login') }}">Login</a></li>
                        <li><a href="{{ url('/register') }}">Register</a></li>
                    @else
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">
                                {{ Auth::user()->username }} <span class="caret"></span>
                            </a>

                            <ul class="dropdown-menu" role="menu">
                                <li>
                                    <a href="{{ route('user.show', ['id' => Auth::user()->id]) }}">
                                        Profile
                                    </a>
                                    
                                </li>

                                <li>
                                    <a href="{{ url('/logout') }}"
                                        onclick="event.preventDefault();
                                                 document.getElementById('logout-form').submit();">
                                        Logout
                                    </a>

                                    <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                        {{ csrf_field() }}
                                    </form>
                                </li>
                            </ul>
                        </li>
                    @endif
                </ul>
            </div>
        </div>
    </nav>

    @yield('top')

    <div class="container">
        @yield('content')
    </div>




    <footer class="footer">
        <div class="container">
            <div class="row">
                <div class="col-xs-4">
                    <a href="{{route('about_us')}}">About Us</a>
                </div>
                <div class="col-xs-4">
                    <a href="{{route('tnc')}}">Terms & Conditions</a>
                </div>
                <div class="col-xs-4">
                    <a href="{{route('faq')}}">FAQ</a>
                </div>
            </div>
        </div>
    </footer>


    @yield('js')



    <!-- Scripts -->
    <script src="/js/app.js"></script>
</body>
</html>