routes/web.php
<?php

use App\Tea;
use App\User;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| This file is where you may define all of the routes that are handled
| by your application. Just tell Laravel the URIs it should respond
| to using a Closure or controller method. Build something great!
|
*/


    // TOLDO rewrite to a controller, have it 
Route::get('/', function () {
    // TODO add top four teas.
    $teas = Tea::all()->sortByDesc('AverageRating')->take(4);
    $users = User::all()->sortByDesc('NumberOfReviews')->take(4);
    return view('pages.index', compact('teas','users'));
})->name('home');


Route::resource('tea', 'TeaController',
    ['except' => 
    ['show']
    ]);

Route::get('tea/{tea}/{slug?}', 'TeaController@show')->name('tea.show');

Route::resource('review', 'ReviewController',
    ['except' => 
    ['create']
    ]);

Route::get('review/create/{id}', 'ReviewController@create')->name('review.create');

Route::resource('user', 'UserController');

Route::get('pages/verified', function () {
    return view('pages.verified');
})->name('verified_review');


Route::get('about_us', function (){
    return view('pages.about_us');
})->name('about_us');
Route::get('faq', function (){
    return view('pages.faq');
})->name('faq');
Route::get('terms_and_conditions', function (){
    return view('pages.tnc');
})->name('tnc');


Route::get('phpinfo', function () {
    return phpinfo();
});



Route::get('/home', 'HomeController@index');

// Let a user add a tearoom (innit).
Route::get('tearoom/main','TearoomController@create');

Route::post('tearoom', 'TearoomController@store');

Route::get('api/v2/users/{user}/reviews', 'UserController@reviews')->name('users.reviews');

Auth::routes();

app/Tea.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Tea extends Model
{

    // lets you edit these things.
    protected $fillable = [
        'name',
        'type',
        'company_id',
        'image_file',
        'image_extension',
    ];

    public function company()
    {
        return $this->belongsTo('App\Company');
    }

    public function reviews()
    {
        return $this->hasMany('App\Review');
    }

    public function getAverageRatingAttribute()
    {
        return round($this->reviews()->avg('rating'));
    }

    public function getImageLocationAttribute()
    {
        return "/images/tea/". $this->image_file . $this->image_extension;
    }

    public function getUrlAttribute()
    {
        return route('tea.show', ['id' => $this->id, 'slug' => $this->slug]);
    }

public function getSlugAttribute()
    {
        return str_slug($this->name);
    }


}

resources/views/pages/about_us.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-xs-12">
        <h2>About {{ config('app.name', 'Laravel') }}</h2><br>

        <img style="width:100px" src='/images/user/pieter.jpg' alt="Image of the best developer ever, Pieter Oliver.">

        <h4>
            Pieter coined the idea as he was drinking some tea. 
            We have top tea scientists working for us to analyse tea.
        </h4>
        <p>
            He looked around and wanted to inspire people to try more varied tea.
            The irony is his favourite tea is a fast black tea with milk.
            He does enjoy a good green tea, camomile, oolong and mint when time permits.
        </p>
    </div>
</div>

@endsection

resources/views/pages/faq.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-xs-12">
        
        <h1>Frequently Asked Questions</h1>


<!-- Shamelessly adapted from www.prepbootstrap.com/bootstrap-template/faq-example -->

    <div class="panel-group" id="accordion">
        <div class="faqHeader"><h3>General questions</h3></div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle" data-toggle="collapse" data-parent="#accordion" href="#collapseOne">Is account registration required?</a>
                </h4>
            </div>
            <div id="collapseOne" class="panel-collapse collapse">
                <div class="panel-body">
                    Account registration at <strong>{{ config('app.name', 'Laravel') }}</strong> is only required if you will be sharing experiences and adding teas you like. 
                    This has mostly been done so you can keep track of your teas, meet and chat with others with a persistent username.
                    We do this to make you happy.
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseTen">Can I submit teas that are not listed?</a>
                </h4>
            </div>
            <div id="collapseTen" class="panel-collapse collapse">
                <div class="panel-body">
                    Of course you can! Look <a href="{{route('tea.create')}}">here</a> for a form where you can add teas.
                    Make sure you've had a search before you add an existing tea, we try out best to add a decent search feature,
                    if you have any feedback send an email to the <a href="mailto:admin@teashare.com?Subject=TeaStore%20Feedback" target="_top">Admin</a>.
                    We value your feedback as a user.
                </div>
            </div>
        </div>
        <div class="panel panel-default">
            <div class="panel-heading">
                <h4 class="panel-title">
                    <a class="accordion-toggle collapsed" data-toggle="collapse" data-parent="#accordion" href="#collapseEleven">
                        Why bother log interesting teas I've drank?
                    </a>
                </h4>
            </div>
            <div id="collapseEleven" class="panel-collapse collapse">
                <div class="panel-body">
                    Why not? If you enjoyed something why would you not share it?
                    77% of people  <!-- TODO turn this into a modal citation that looks good. -->
                    <sup>
                        <button type="button" class="btn" data-toggle="modal" data-target="#myModal">
                          1
                        </button>
                    </sup>
                    review something before buying it online, 
                    why not help your community by contributing to it's collective palate.
                </div>
            </div>
        </div>
    </div>

<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      </div>
      <div class="modal-body">
        Cited from <a href="http://www.business.com/online-marketing/77-percent-of-people-read-online-reviews-before-buying-are-they-finding-you/">
            buisness.com
        </a>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>



    </div>
</div>

@endsection

resources/views/pages/index.blade.php
@extends('layouts.app')

@section('heading')
  <link href="/css/main_page.css" rel="stylesheet">
@endsection


@section('top')


    <!-- Carousel
    ================================================== -->
    <div id="myCarousel" class="carousel slide" data-ride="carousel">
      <!-- Indicators -->
      <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
      </ol>
      <div class="carousel-inner" role="listbox">
        <div class="item active">
          <div class="container">
            <div class="carousel-main-page">
              <h1><br><br><br></h1> <!-- This is very hackey, took 30min to not do. -->
              <h1>Tea-Share</h1>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="container carosel-daddy">
            <div class="carousel-main-page">
              <div>
                <h1><br><br><br></h1>
                <h3>
                  Share your experiences with the different teas you have.
                </h3>
              </div>
            </div>
          </div>
        </div>
        <div class="item">
          <div class="container carosel-daddy">
            <div class="carousel-main-page">
              <h1><br><br><br></h1>
              <h2>Share you favourite teas on social media</h2>
              <h4>Twitter, Facebook and Google+!</h4>
            </div>
          </div>
        </div>
      </div>
      <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
    </div><!-- /.carousel -->


@endsection

@section('content')

<div class="jumbotron">
  <h1>
    @if (Auth::user())
      Discover more teas to add to your favourites.
    @else
      Find an interesting tea!
    @endif
  </h1>

    <div class="row">
        @foreach ($teas as $tea)
            <div class="col-xs-6 col-sm-4 col-md-3 tea-box">
                <a href="{{ $tea->url }}" class="thumbnail">
                    <img src='{{$tea->ImageLocation}}' alt="image of {{ $tea->name }}" class="tea_image">
                </a> 
                <div class="caption">
                    {{ $tea->name }}
                    is a {{ $tea->type }} tea, 
                    by <a href="{{$tea->company->url}}" target="_blank">{{$tea->company->name }}</a>.
                    
                    <h3 class="text-center">
                        {{count($tea->reviews)}} 
                        <span class="glyphicon glyphicon-comment" aria-hidden="true"></span>
                    </h3>
                </div>


            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="{{$tea->averageRating}}" aria-valuemin="0" aria-valuemax="100" style="width: {{$tea->averageRating}}%;">
                    {{$tea->averageRating}}
                </div>
            </div>

            </div>
        @endforeach
    </div>
</div>


<div class="jumbotron">
  <h1>
    @if (Auth::user())
      Interact with other users!
    @else
      Join our active users!
    @endif
  </h1>

    <div class="row">
        @foreach ($users as $user)
            <div class="col-xs-6 col-sm-4 col-md-3">
                <a href="{{ route('user.show', $user->id) }}" class="thumbnail">
                    <img src="{{ url($user->ImageLocation) }}" alt="{{ $user->username }}'s' avatar image">
                </a>
                <div class="caption">
                    <h3> {{ $user->username }} </h3>
                    Reviews  {{ count($user->reviews) }}
                </div>
            </div>
        @endforeach
    </div>
</div>



@endsection

resources/views/pages/tnc.blade.php
@extends('layouts.app')

@section('content')

<div class="row">
    <div class="col-xs-12">

        <div class="page-header">
                <h2>1. General Terms</h2>
        </div>
        <p><strong>1.1</strong> 
            By accessing and using {{ config('app.name', 'Laravel') }}, you confirm that you are in agreement with and bound by the terms and conditions contained in the Terms Of Use outlined below. 
            These terms apply to the entire website and any email or other type of communication between you and {{ config('app.name', 'Laravel') }}.
        </p>

        <div class="page-header term">
                <h2>2. Users</h2>
        </div>
        <p><strong>2.1</strong> All users of {{ config('app.name', 'Laravel') }} will be nice to each other. If you wouldn't say it to your mother, don't say it here.</p>
        <p><strong>2.2</strong> {{ config('app.name', 'Laravel') }} is not responsible for any review by users, we will try to check that there are not financial interests undisclosed but this is a challenge.</p>


        <div class="page-header term">
                <h2>3. Security</h2>
        </div>
        <p><strong>3.1</strong> {{ config('app.name', 'Laravel') }} securely stores your passwords and details. Feel free to contact us about our security policies.</p>
        
        <div class="page-header term">
                <h2>4. Reviews</h2>
        </div>
        <p><strong>4.1</strong> As stated on our <a href="{{ route('verified_review') }}">verified review</a> page, {{ config('app.name', 'Laravel') }}
        tries to weed out bias, rude and false reviews. If any slip through, let us know.</p>

        <div class="page-header term">
                <h2>5. Admin Privileges</h2>
        </div>
        <p>
            <strong>5.1</strong> As the dictator at the helm, I reserve the right to settle disputes between users as I see fit.
            If it requires me to go <a href="https://en.wikipedia.org/wiki/Judgment_of_Solomon">King Solomon</a>, so be it.
        </p>


        <div class="page-header changes">
                <h2>Changes to terms</h2>
        </div>
        <p>If we change our terms of use we will post those changes on this page. Registered users might be sent an email that outlines changes made to the terms of use, if Pieter add that feature.</p>
    </div>
</div>


<!-- TOLDO Add a better terms of conditions. -->

<!-- 
    a licence of the copyright in the website (and restrictions on what may be done with the material on the website);
    a disclaimer of liability;
    a clause governing the use of passwords and restricted areas of the website;
    an acceptable use clause;
    a variation clause;
    an entire agreement clause;
    a clause specifying the applicable law and the jurisdiction in which disputes will be decided; and
    a provision specifying some of the information which needs to be disclosed under the Ecommerce Regulations.
 -->



@endsection

resources/views/pages/verified.blade.php
@extends('layouts.app')

@section('content')

<h1>
    What is a verified review?
</h1>

<p>
    A verified review is one where we can guarantee that the item in question was purchased by the user. 
    We trust users are disclosing any financial interests.
    As per the terms of service, users found posting fake reviews will be named, shame and highlighted as big fat phonies!
</p>


@stop